# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sven Schmit
email: lastname @ stanford.edu
description: > # this means to ignore newlines until "baseurl:"
    Personal website Sven Schmit, PhD student at Stanford University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.stanford.edu/~schmit" # the base hostname & protocol for your site
twitter_username: spschmit
github_username: schmit

# Build settings
markdown: kramdown
highlighter: true
