# Site settings

title: Sven Schmit # Title of your site
email: schmit [at] stanford.edu # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Personal webpage Sven Schmit, PhD student at ICME, Stanford.
  Interested in Statistics, Machine Learning, Algorithms, Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.stanford.edu/~schmit" # the base hostname & protocol for your site

# Social links.

twitter_username:     spschmit
github_username:      schmit
linkedin_username:    svenschmit
google_plus_username:
facebook_username:
dribbble_username:

# Build settings
markdown: kramdown
