# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-BGD8S3HYW2'

menu:
- {name: 'About',   url: 'about'}
- {name: 'Research', url: 'research'}
- {name: 'Teaching', url: 'teaching'}
- {name: 'Writing', url: 'writing'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/schmit'}
- {icon: 'twitter',    link: 'https://twitter.com/spschmit'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/svenschmit/'}
- {icon: 'envelope',   link: 'mailto:hello@svenschmit.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
